### ISSUE TITLE
📚 [Contribution] ebook2audiobook roadmap

### ISSUE THREAD

**Issue by DrewThomasson** [DrewThomasson/ebook2audiobook#32]
## All Features open to public Contributions ⭐
- [x] -h -help parameter info in different languages
- [x] Notebooks Folder [Talked about here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/5#issuecomment-2408773254)
- [x] Make Chinese text splitting not split words and improve pause timing [Talked about here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/18#issuecomment-2401154894)
- [ ] Get Kaggel Notebook working (Needs to be giving dropdown menus to interact with the headless version) [Talked about here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/5#issuecomment-2408773254)
- [x] Get Working Google Colab Notebook [Talked about here
](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/5#issuecomment-2408773254)
- [ ] [Make a ios app](https://github.com/DrewThomasson/ebook2audiobook/pull/35#issuecomment-2496495212)
- [ ] [Make an android app](https://github.com/DrewThomasson/ebook2audiobook/pull/35#issuecomment-2496495212)
## Wanted Extra Parameters
- [ ] [Translate from translate the full ebook to X lang and audiobook it, output original ebookfile, audiobook file, and translated ebook file](https://github.com/DrewThomasson/ebook2audiobook/pull/35#issuecomment-2496305631)
- [x] Make parameter for specifying output audio file format
- [ ] The F5-TTS model referenced [here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/38#issuecomment-2453224267)
- [x] Make ebook input parameter accept a list of files for multiple files.
- [x] Make a way for multiple lines to have audio generated at a time using multiple instances of coqui tts running for more beefy hardware.
- [x] Make ebook input parameter accept a folder containing ebook files to auto-run through.
- [ ] OCR for PDF files (as a Parameter) [Talked about here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/21)
- [x] Add a force use device (cpu or GPU) (This will force set the device at the top of the script) [Talked about here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/17#issuecomment-2400976734)(currently being added by @ROBERT-MCDOWELL) [ref here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/17#issuecomment-2412577620)
- [x] Use [Deepfilternet2](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/33#issuecomment-2412883354) to de-noise any reference audio for voice cloning, [demo huggingfacespace using it](https://huggingface.co/spaces/drewThomasson/DeepFilterNet2_no_limit), Talked about [here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/33#issuecomment-2412883354)
- [x] Custom model dir input for pointing to a folder containing all of the custom model files if available instead of having to point to each model file individually
- [ ] Change voices per chapter parameter [Talked about here](https://github.com/DrewThomasson/ebook2audiobookXTTS/issues/32#issuecomment-2413998689)

## My Other Repos I Want to Integrate into the App for Extra Options :)
- [ ] Add app parameter that launches the [ebook2audiobookpiper-tts GUI](https://github.com/DrewThomasson/ebook2audiobookpiper-tts).(Piper tts appears to have issues working in ARM (apple silicon)MAC  But runs fine in the docker on ARM)
- [ ] Add app parameter that launches the [ebook2audiobookstyletts2 GUI](https://github.com/DrewThomasson/ebook2audiobookSTYLETTS2).
- [ ] Add app parameter that launches the [ebook2audiobook-espeak GUI](https://github.com/DrewThomasson/ebook2audiobookEspeak).
- [ ] Add app parameter that launches the [FineTune XTTS GUI](https://github.com/DrewThomasson/finetuneXtts_apple_silicone). 
- [ ] Add app parameter for using Barktts [documentation from coqui tts](https://docs.coqui.ai/en/latest/models/bark.html)

## Create a standard function for load_model() and inference_model() for:
- [x] ⓍXTTSv2
- [ ] Styletts2
- [ ] 🪈 Piper-tts
- [x] 🐶 Bark tts
- [x] Fairseq
- [x] Vits
- [x] YourTTS
- [ ] [Tortoise](https://github.com/neonbjb/tortoise-tts)
- [ ] [Glow-TTS](https://arxiv.org/abs/2005.11129)
- [ ] [SC-GlowTTS](https://arxiv.org/abs/2104.05557)
- [ ] [Tacotron](https://arxiv.org/abs/1703.10135) 
- [ ] [Tacotron2](https://arxiv.org/abs/1712.05884)
- [ ] [Speedy-Speech](https://arxiv.org/abs/2008.03802)
- [ ] [Align-TTS](https://arxiv.org/abs/2003.01950)
- [ ] [FastPitch](https://arxiv.org/pdf/2006.06873.pdf)
- [ ] [FastSpeech](https://arxiv.org/abs/1905.09263)
- [ ] [FastSpeech2](https://arxiv.org/abs/2006.04558)
- [ ] [Delightful TTS](https://arxiv.org/abs/2110.12612)
- [ ] Zonos
- [ ] F5-TTS
- [ ] Cozy-voice
- [ ] Spark TTS

## Create Readme in these languages

- [x] Arabic (ara)
- [x] Chinese (zho)
- [x] English (eng)
- [x] Spanish (spa)
- [x] French (fra)
- [x] German (deu)
- [x] Italian (ita)
- [x] Portuguese (por)
- [x] Polish (pol)
- [x] Turkish (tur)
- [x] Russian (rus)
- [x] Dutch (nld)
- [x] Czech (ces)
- [x] Japanese (jpn)
- [x] Hindi (hin)
- [x] Bengali (ben)
- [x] Hungarian (hun)
- [x] Korean (kor)
- [x] Vietnamese (vie)
- [x] Swedish (swe)
- [x] Persian (fas)
- [x] Yoruba (yor)
- [x] Swahili (swa)
- [x] Indonesian (ind)
- [x] Slovak (slk)
- [x] Croatian (hrv)   

## Binary builds Working pyinstaller script for:

- [x] 🍎 Mac Intel x86
- [x] 🪟 Windows x86
- [x] 🐧 Linux x86
- [x] 🖥️🍏 Apple Silicon Mac
- [x] 🪟💪 ARM Windows
- [x] 🐧💪 ARM Linux

## 🐍 Single pip command install that works for:
- being overseen by @ROBERT-MCDOWELL
- [x] 🍎 Mac Intel x86
- [x] 🪟 Windows x86
- [x] 🐧 Linux x86
- [x] 🖥️🍏 Apple Silicon Mac
- [x] 🪟💪 ARM Windows
- [x] 🐧💪 ARM Linux

## Extra Overkill for training models and such (All supported Coqui-tts models and piper-tts in one easy command) 
- For info about this @DrewThomasson, he is currently working on the development of this, [work-in-progress-repo here](https://github.com/DrewThomasson/Universal_TTS_Finetune)
- [ ] Make a easy to use training gui for all coqui-tts models in the ljspeech format training recipes [here from coqui tts](https://github.com/coqui-ai/TTS/tree/dev/recipes/ljspeech)

## For higher level developers:
- [ ] Integrate VoxNovel experimental functionality into this 🤷 eventually. . .

## Wanted Auto-testing scripts for development

- [x] Standard model headless run through every language sample [Samples located here](https://github.com/DrewThomasson/ebook2audiobookXTTS/tree/main)

@DrewThomasson if you want to help out at all! 😃

**Comment by ROBERT-MCDOWELL** [comment]
gees. calm down heh :)

**Comment by ROBERT-MCDOWELL** [comment]
Another interesting option would be to change voices between chapters. for i.e.:
--voice_mapping {"chapters": {1:"john.wav",2:"stella.wav",3:"child.wav",4:"random"} }
so the selected chapters will see their voice mapped, others will keep the main --voice intact.
implemented on v26.5.10+ in gradio and headless with --voice_map

**Comment by DrewThomasson** [comment]
> Another interesting option would be to change voices between chapters. for i.e.: --voice_mapping {"chapters": {1:"john.wav",2:"stella.wav",3:"child.wav",4:"random"} } so the selected chapters will see their voice mapped, others will keep the main --voice intact.

@ROBERT-MCDOWELL Added to roadmap checklist

**Comment by DrewThomasson** [comment]
Compare tts

https://github.com/DrewThomasson/ebook2audiobook/pull/35#issuecomment-2492676036

**Comment by DrewThomasson** [comment]
Translate ebook to X language
https://github.com/DrewThomasson/ebook2audiobook/pull/35#issuecomment-2496305631

**Comment by geneliu** [comment]
Integration with https://github.com/janeczku/calibre-web

**Comment by ROBERT-MCDOWELL** [comment]
@geneliu how you would see it?

**Comment by DrewThomasson** [comment]
https://github.com/DrewThomasson/ebook2audiobook/discussions/179#discussion-7771811

**Comment by DrewThomasson** [comment]
More tts models I will look at figuring out how to add to coqui tts (hopefully if I can figure it out) as well as my ultimate goal of making a PR to coqui to add styletts2

https://github.com/karim23657/awesome-Persian-Speech?tab=readme-ov-file

**Comment by DrewThomasson** [comment]
Potentially adding epub3 as a output format

Example being [storyteller](https://smoores.gitlab.io/storyteller/)

https://www.reddit.com/r/Python/s/vt8DsiogW8

**Comment by ROBERT-MCDOWELL** [comment]
> Potentially adding epub3 as a output format
> 
> Example being [storyteller](https://smoores.gitlab.io/storyteller/)
> 
> https://www.reddit.com/r/Python/s/vt8DsiogW8

we can do it already, it needs just to specify epub3 as output extension at the conversion.

**Comment by ROBERT-MCDOWELL** [comment]
correction, It does not need to add the extension, just add some options... ready for next PR.

**Comment by AlexiaChen** [comment]
https://github.com/[stepfun-ai/Step-Audio](https://github.com/stepfun-ai/Step-Audio) Step-Audio  Does any helpful  for this project?

**Comment by DrewThomasson** [comment]
@AlexiaChen 
So does that modify [cosyVoice](https://github.com/FunAudioLLM/CosyVoice) to add more emotional or contextual characteristics to the tts output?

**Comment by AlexiaChen** [comment]
> [@AlexiaChen](https://github.com/AlexiaChen) So does that modify [cosyVoice](https://github.com/FunAudioLLM/CosyVoice) to add more emotional or contextual characteristics to the tts output? or...?

@DrewThomasson   Maybe,  Quote from  README:     "supporting multilingual conversations (e.g., Chinese, English, Japanese), emotional tones (e.g., joy/sadness), regional dialects (e.g., Cantonese/Sichuanese)"   But I do not know if it is support from modify cosyVoice you mentioned above

**Comment by ROBERT-MCDOWELL** [comment]
this can ben an interesting post effect ot give more wanted life to the text indeed.
I put it on my list

**Comment by SinghArindam** [comment]
Kokoro tts 82M

**Comment by taralika** [comment]
> Kokoro tts 82M

here are some options with Kokoro tts already integrated:
https://github.com/santinic/audiblez
https://github.com/aedocw/epub2tts
https://github.com/nazdridoy/kokoro-tts

**Comment by ROBERT-MCDOWELL** [comment]
kokoro is using F5-tts engine, so the best would be to integrate F5-tts direcctly without to add layers of python programs

**Comment by taralika** [comment]
> kokoro is using F5-tts or style-tts engine, so the best would be to integrate F5-tts direcctly without to add layers of python programs

kokoro is based on styletts2 (but not exactly the same); kokoro is lightweight and its local inference is quite fast.. IMHO it'd be helpful to integrate both, kokoro as well as f5-tts (someone seems to have already done an f5-tts integration here: https://github.com/quantumlump/eBook_to_Audiobook_with_F5-TTS )

**Comment by ROBERT-MCDOWELL** [comment]
new projects are growing like mushroom indeed. I will take a look. meanwhile we need a very stable version before to go further.
I'm waiting an answer to my question on your pull request to continue to patch bark thanks

**Comment by taralika** [comment]
> I'm waiting an answer to my question on your pull request to continue to patch bark thanks

I responded yesterday :) https://github.com/DrewThomasson/ebook2audiobook/pull/711#issuecomment-2869462768

**Comment by ROBERT-MCDOWELL** [comment]
ok didn't see it sorry. I just pusehd now. thanks to try again. Frustrated I'm to not be able to test on my 18 years old laptop btw ;)

**Comment by taralika** [comment]
> > kokoro is using F5-tts or style-tts engine, so the best would be to integrate F5-tts direcctly without to add layers of python programs
> 
> kokoro is based on styletts2 (but not exactly the same); kokoro is lightweight and its local inference is quite fast.. IMHO it'd be helpful to integrate both, kokoro as well as f5-tts (someone seems to have already done an f5-tts integration here: https://github.com/quantumlump/eBook_to_Audiobook_with_F5-TTS )

Another one I'd add to this list is [Zonos](https://github.com/Zyphra/Zonos).. the speech is more expressive with emotion inference

**Comment by ROBERT-MCDOWELL** [comment]
it's on the list above already ;). Orpheus is very promising too.

**Comment by AlexiaChen** [comment]
MiniMax  Speech-02 TTS-model released

**Comment by Crushedice** [comment]
Kokoro. Please. Its pretty good from what i saw, and "custom upload model" doesnt work at all

**Comment by ROBERT-MCDOWELL** [comment]
what do you mean by  "custom upload model" doesnt work at all? this is for xttsv2 only! please don't hijack the roadmap.
if you have any questions of how to use custom model uploade (FOR XTTS) so go to discussions.

**Comment by ATAD4NRY4N** [comment]
Please consider adding support for voices generated using Nari Dia 1.6B, https://github.com/nari-labs/dia

**Comment by FuxorLuck** [comment]
> Another interesting option would be to change voices between chapters. for i.e.: --voice_mapping {"chapters": {1:"john.wav",2:"stella.wav",3:"child.wav",4:"random"} } so the selected chapters will see their voice mapped, others will keep the main --voice intact.

What about changing the voice for each character?

Let the AI read the ebook and determine which line belongs to each character then the user can choose which voice to give each character.

**Comment by ATAD4NRY4N** [comment]
> > Another interesting option would be to change voices between chapters. for i.e.: --voice_mapping {"chapters": {1:"john.wav",2:"stella.wav",3:"child.wav",4:"random"} } so the selected chapters will see their voice mapped, others will keep the main --voice intact.
> 
> What about changing the voice for each character?
> 
> Let the AI read the ebook and determine which line belongs to each character then the user can choose which voice to give each character.

[VoxNovel](https://github.com/DrewThomasson/VoxNovel), another repo from the same OP, Has the capability to have different voices per character.
Seems like an earlier project that ebook2audiobook. I agree, it would be great if some of the features from VoxNovel could be migrated to this project.

**Comment by ROBERT-MCDOWELL** [comment]
@AlexiaChen 
not all books have characters, not all books is a romance or discussion, tell me how you manage a scientific, political, technical book with "characters" and how you detect it if it's not mentioned in the original text?and you want all that for free?  this feature has been asked many many times, you should read first the discussions section history.  Since we started ebook2audiobook despite of 10k stars and many forks, we received until now zero donation nor bounties. Today I pass 90% of my time to develop for you guys since 8 months for free. thank you all fellow humans to help my family and I to survive.

**Comment by ROBERT-MCDOWELL** [comment]
> > Another interesting option would be to change voices between chapters. for i.e.: --voice_mapping {"chapters": {1:"john.wav",2:"stella.wav",3:"child.wav",4:"random"} } so the selected chapters will see their voice mapped, others will keep the main --voice intact.
> 
> What about changing the voice for each character?
> 
> Let the AI read the ebook and determine which line belongs to each character then the user can choose which voice to give each character.


Ok make a PR I will be happy to merge it thanks

**Comment by ROBERT-MCDOWELL** [comment]
> Please consider adding support for voices generated using Nari Dia 1.6B, https://github.com/nari-labs/dia

nari-dia is not multilingual unfortunately.

**Comment by ricardonevesmusic** [comment]
Maybe chapter detection and selection for eBooks: mostly EPUB, but MOBI/AZW3/PDF/DOCX would be nice.

It would detect the book chapters if those are properly implemented and present in the book structure and then you could choose to only convert specific chapters or all chapters.

This would be a really nice addition to it and would make the user's life way easier and manageable.

Yes, anything that could properly store the ebook chapters inside it, could be considered a valid and supported book format/file.

That's basically it.

I think I've seen this implemented elsewhere on Hugginface, so if I could find that reference, it would make things way easier.

**Comment by ROBERT-MCDOWELL** [comment]
it's on rails.

**Comment by McCzarny** [comment]
Hello, some time ago I've forked the repo to add support for GoogleDrive in the colab and conversion resume in case of an error (e.g. when a session is interrupted). Would it fit to your roadmap? The general use case was to be able to convert an ebook, even it was not possible to finish it in a single session.

Another topic - could you consider adding to the roadmap a general refactor? `core.py` is huge and methods there are built with a big number of nested `if`s . It makes it hard to understand and update the code. Of coarse I would be happy to help with it.

**Comment by ricardonevesmusic** [comment]
> Hello, some time ago I've forked the repo to add support for GoogleDrive in the colab and conversion resume in case of an error (e.g. when a session is interrupted). Would it fit to your roadmap? The general use case was to be able to convert an ebook, even it was not possible to finish it in a single session.
> 
> Another topic - could you consider adding to the roadmap a general refactor? `core.py` is huge and methods there are built with a big number of nested `if`s . It makes it hard to understand and update the code. Of coarse I would be happy to help with it.

The only solution is to adapt and tweak the text in the book (by keeping only the chapters you still need to convert and removing everything else).

It's not possible to preserve progress in Google Colab: it will attribute you a new empty machine every time you get kicked out of a session or start a new one.

So, there's nothing the developers can do: as it's a platform limitation, not a program one.

That's basically it.

**Comment by McCzarny** [comment]
I overcame this limitation by mounting a Google Drive folder as a working directory for the tool. You can find a rough implementation of this here: https://github.com/DrewThomasson/ebook2audiobook/compare/main...McCzarny:ebook2audiobook:main.

Look for `GOOGLE_DRIVE_PATH`.

**Comment by ROBERT-MCDOWELL** [comment]
> Hello, some time ago I've forked the repo to add support for GoogleDrive in the colab and conversion resume in case of an error (e.g. when a session is interrupted). Would it fit to your roadmap? The general use case was to be able to convert an ebook, even it was not possible to finish it in a single session.
> 
> Another topic - could you consider adding to the roadmap a general refactor? `core.py` is huge and methods there are built with a big number of nested `if`s . It makes it hard to understand and update the code. Of coarse I would be happy to help with it.

E2A resumes a failed/cancel/crashed conversion simply by checking the checksum with the original source file and the copy in tmp and if it is exactly the same so it checks the sentences converted in tmp/*/sentences folder in sync with the .json where all the sentences are in text. so if colab keep the tmp folder intact there is no reason to do special code for colab.

update: available now ince v26.3.10+

**Comment by ROBERT-MCDOWELL** [comment]
and many users don't take a little time to read the README or the end lof log at each conversion where they could read:
" to resume a session in headless mode just provide --session xxxxxxx"
in gradio GUI mode, if colab keep the gradio/GUI page cookies, it's automatic.
if the cookies are wiped out every time colab restarts so the session is wiped out too and there is no way to get the session back,
unless if I allow the user to enter manually the previous session in the session field. but doing that open doors to security breach...

update: available now on gradio since v26.5.10+, just click on the lock button beside of the session.

**Comment by McCzarny** [comment]
> unless if I allow the user to enter manually the previous session in the session field. but doing that open doors to security breach...

Thank you for the answers! Regarding session id - I think there is no point in treating it as secure info. The ID is too big to simply guess existing session ID, also making session field read only prevents non-technical people. The id comes from local storage that is editable by the user, if there would be a bad actor, they will be able to freely change the session id to anything.

update: available now on gradio since v26.5.10+, just click on the lock button beside of the session.

**Comment by albertoZurini** [comment]
Hi! I'd like to help integrating Qwen3. I joined the discord, but I didn't see a developers channel. How can I help?

PS: I can also translate the Readme to Italian 🤌

**Comment by ROBERT-MCDOWELL** [comment]
@albertoZurini 
> Hi! I'd like to help integrating Qwen3. I joined the discord, but I didn't see a developers channel. How can I help?

you can but must respect the code normalization at its best. I will create a readme dev code for that
updated: it's now on README

> I can also translate the Readme to Italian

you're welcome to do it!
